TODO note

diff --git a/scripts/kong_install_service_and_route b/scripts/kong_install_service_and_route
--- a/scripts/kong_install_service_and_route
+++ b/scripts/kong_install_service_and_route
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+#TODO add support for service_path paramater
+
 #Example:
 #kong_install_service_and_route http://kong:8001 portainer http portainer 9000 https /portainer
 
@@ -27,10 +29,18 @@ CREATE_SERVICE_OUTPUT=$(curl -sS --fail -X POST \
                      --data "port=${SERVICE_PORT}")
 ret=$?
 if [ $ret -ne 0 ]; then
+  if [ "E$(echo 'a')" = "E" ]; then
+    echo "Create service failed - ${ret}"
+    echo "Output: ${CREATE_SERVICE_OUTPUT}"
+    echo ""
+    exit 1
+  fi
   echo "Create service failed - ${ret}"
+  echo "detected the service already exists exiting with success status"
+  echo "to prevent docker from retrying this service"
+  echo "not attempting to create any routes"
   echo "Output: ${CREATE_SERVICE_OUTPUT}"
-  echo ""
-  exit 1
+  exit 0
 fi
 
 #echo "OUTPUT WAS"
