Making process more robust

diff --git a/scripts/kong_install_service_and_route b/scripts/kong_install_service_and_route
--- a/scripts/kong_install_service_and_route
+++ b/scripts/kong_install_service_and_route
@@ -21,45 +21,70 @@ if [ "E${ROUTE_PATHS}" = "E" ]; then
   exit 1
 fi
 
-
-CREATE_SERVICE_OUTPUT=$(curl -sS --fail -X POST \
-                     --url ${KONG_URL}/services/ \
-                     --data "name=${SERVICE_NAME}" \
-                     --data "protocol=${SERVICE_PROTOCOL}" \
-                     --data "host=${SERVICE_HOST}" \
-                     --data "port=${SERVICE_PORT}" \
-                     --data "path=${SERVICE_PATH}" \
-                      2>&1)
-ret=$?
-if [ $ret -ne 0 ]; then
-  TMP=$(echo ${CREATE_SERVICE_OUTPUT} | grep 'curl: (22) The requested URL returned error: 409 Conflict' )
-  if [ "E${TMP}" = "E" ]; then
-    echo "Create service failed - ${ret}"
-    echo "Output: ${CREATE_SERVICE_OUTPUT}"
+SERVICE_JSON=$(curl -sS --fail -X GET --url ${KONG_URL}/services/${SERVICE_NAME} 2>&1)
+RET=$?
+SERVICE_EXISTS_IN_KONG=1
+if [ ${RET} -ne 0 ]; then
+  SERVICE_EXISTS_IN_KONG=0
+  echo "Service not found in kong"
+  echo "Output: ${SERVICE_JSON}"
+  echo ""
+  TMP=$(echo ${SERVICE_JSON} | grep 'Connection refused' )
+  if [ "E${TMP}" != "E" ]; then
+    echo "Detected connection refused"
+    echo "Kong isn't running - terminating ${0}"
     echo ""
     exit 1
   fi
-  echo "Create service failed - ${ret}"
-  echo "detected the service already exists exiting with success status"
-  echo "to prevent docker from retrying this service"
-  echo "not attempting to create any routes"
-  echo "Output: ${CREATE_SERVICE_OUTPUT}"
-  echo ""
-  echo "end of ${0}"
-  exit 0
 fi
+
+if [ ${SERVICE_EXISTS_IN_KONG} -eq 0 ]; then
+  SERVICE_JSON=$(curl -sS --fail -X POST \
+                       --url ${KONG_URL}/services/ \
+                       --data "name=${SERVICE_NAME}" \
+                       --data "protocol=${SERVICE_PROTOCOL}" \
+                       --data "host=${SERVICE_HOST}" \
+                       --data "port=${SERVICE_PORT}" \
+                       --data "path=${SERVICE_PATH}" \
+                        2>&1)
+  ret=$?
+  if [ $ret -ne 0 ]; then
+    echo "Create service failed - ${ret}"
+    echo "Output: ${SERVICE_JSON}"
+    echo ""
+    exit 1
+  fi
+fi
+
 
 #echo "OUTPUT WAS"
 #echo "${CREATE_SERVICE_OUTPUT}"
 #echo "END"
 #
-SERVICE_ID=$(echo ${CREATE_SERVICE_OUTPUT} | python -c "import sys, json; print json.load(sys.stdin)['id']")
+SERVICE_ID=$(echo ${SERVICE_JSON} | python -c "import sys, json; print json.load(sys.stdin)['id']")
 ret=$?
 if [ $ret -ne 0 ]; then
   echo "Could not find the service id"
   exit 1
 fi
 echo " - service id: ${SERVICE_ID}"
+
+ROUTE_LIST_JSON=$(curl -sS --fail -X GET --url ${KONG_URL}/services/${SERVICE_NAME}/routes 2>&1)
+RET=$?
+if [ ${RET} -ne 0 ]; then
+  echo "Query route failed - ${ret}"
+  echo "Output: ${ROUTE_LIST_JSON}"
+  exit 1
+fi
+
+NUMBER_OF_ROUTES=$(echo ${ROUTE_LIST_JSON} | python -c "import sys, json; print len(json.load(sys.stdin)['data'])")
+echo " - Service has ${NUMBER_OF_ROUTES} routes"
+
+if [ ${NUMBER_OF_ROUTES} -ne 0 ]; then
+  echo "Terminating as service already has routes"
+  echo "End of ${0}"
+  exit 0
+fi
 
 CREATE_ROUTE_CMD="curl -sS --fail -X POST \
 --url ${KONG_URL}/routes/ \
@@ -75,6 +100,7 @@ if [ $ret -ne 0 ]; then
   echo "Cmd: ${CREATE_ROUTE_CMD}"
   exit 1
 fi
+echo "Route POST returned ${RET}"
 
 echo "${0} completed sucessfully"
 
